import { useNavigate, useParams } from "react-router-dom";
import { ReactCompareSlider, ReactCompareSliderImage } from "react-compare-slider";
import ScoreGauge from "@/components/ScoreGauge";
import MetricBar from "@/components/MetricBar";
import { mockScores, mockRecommendation } from "@/data/mockData";

const SharePage = () => {
  const navigate = useNavigate();
  const { id } = useParams();

  // TODO: Replace hardcoded data with fetch to GET /share/{id} → returns public scan data from Supabase

  return (
    <div className="min-h-screen bg-background-dark font-display">
      {/* Minimal navbar */}
      <div className="flex items-center justify-between px-6 py-4 border-b border-white/5">
        <div className="flex items-center gap-2">
          <span className="material-symbols-outlined text-primary">flare</span>
          <span className="font-black text-ivory">Dental Vision</span>
        </div>
        <button
          onClick={() => navigate("/")}
          className="px-4 py-2 bg-primary text-white rounded-full text-xs font-bold hover:opacity-90 transition-opacity"
        >
          Analyse Your Smile →
        </button>
      </div>

      <div className="max-w-2xl mx-auto px-6 py-10">
        {/* Banner */}
        <div className="bg-primary/10 border border-primary/20 rounded-2xl p-4 flex items-center gap-3 mb-8">
          <span className="material-symbols-outlined text-primary">share</span>
          <span className="text-sm text-slate-300">You're viewing a shared Dental Vision scan report.</span>
          <button onClick={() => navigate("/")} className="text-primary font-bold underline text-sm ml-auto shrink-0">
            Try it free →
          </button>
        </div>

        {/* Score card */}
        <div className="bg-card-dark rounded-3xl p-8 flex flex-col items-center gap-6 border border-white/10 shadow-2xl">
          <ScoreGauge score={mockScores.overall} size={148} strokeWidth={12} />
          <span className="text-[10px] font-black uppercase tracking-widest text-ivory">SMILE HEALTH SCORE</span>

          <div className="w-full grid grid-cols-2 gap-3">
            <MetricBar label="Alignment" value={mockScores.alignment} icon="straighten" />
            <MetricBar label="Symmetry" value={mockScores.symmetry} icon="compare_arrows" />
            <MetricBar label="Whiteness" value={mockScores.whiteness} icon="brightness_high" />
            <MetricBar label="Spacing" value={mockScores.spacing} icon="space_bar" />
          </div>

          <span className="text-xs text-slate-600">Scanned on May 12, 2025</span>
          <p className="text-[10px] text-slate-600 text-center">
            This score was generated by Dental Vision AI and is for informational purposes only.
          </p>
        </div>

        {/* Before/After slider */}
        <div className="mt-8 rounded-2xl overflow-hidden border border-white/10">
          <ReactCompareSlider
            itemOne={
              <div className="relative w-full h-full">
                <ReactCompareSliderImage
                  src="https://images.unsplash.com/photo-1606811841689-23dfddce3e95?w=800"
                  alt="Original"
                  style={{ objectFit: "cover" }}
                />
                <span className="absolute bottom-4 left-4 bg-black text-white px-3 py-1 text-[10px] font-bold uppercase">ORIGINAL</span>
              </div>
            }
            itemTwo={
              <div className="relative w-full h-full">
                <ReactCompareSliderImage
                  src="https://images.unsplash.com/photo-1570172619644-dfd03ed5d881?w=800"
                  alt="Simulation"
                  style={{ objectFit: "cover" }}
                />
                <span className="absolute bottom-4 right-4 bg-primary text-white px-3 py-1 text-[10px] font-bold uppercase">SIMULATION</span>
              </div>
            }
            style={{ width: "100%", aspectRatio: "4/3" }}
            handle={
              <div className="bg-card-dark border-2 border-black p-1 flex items-center justify-center">
                <span className="material-symbols-outlined text-ivory text-sm">unfold_more_double</span>
              </div>
            }
          />
        </div>

        {/* Recommendation */}
        {/* TODO: from share/{id} public endpoint */}
        <div className="bg-primary/10 border border-primary/20 rounded-2xl p-6 mt-8">
          <div className="flex items-center gap-3 mb-3">
            <span className="material-symbols-outlined text-primary">lightbulb</span>
            <span className="text-sm font-black uppercase text-ivory">AI RECOMMENDATION</span>
          </div>
          <p className="text-sm text-ivory leading-relaxed">{mockRecommendation.summary}</p>
        </div>

        {/* CTA */}
        <div className="flex flex-col items-center gap-4 mt-10 text-center">
          <h3 className="text-xl font-black text-ivory">Want to know your smile score?</h3>
          <p className="text-sm text-slate-400">Get your free AI dental analysis in under 60 seconds.</p>
          <button
            onClick={() => navigate("/")}
            className="px-8 py-3 bg-primary text-white rounded-full font-black text-sm hover:opacity-90 transition-opacity"
          >
            Analyse My Smile — It's Free
          </button>
        </div>
      </div>
    </div>
  );
};

export default SharePage;
